site_name: LoRaBridge Literature
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
copyright: Copyright &copy; 2025 St. Pölten University of Applied Sciences
repo_url: https://github.com/lorabridge2
use_directory_urls: false
repo_url: https://github.com/lorabridge
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - include-markdown
  - privacy
  - search
  - glightbox
nav:
  - index.md
  - Setup:
    - setup/Installation.md
    - setup/How-to-use.md
    - setup/Troubleshooting.md
    - setup/config.md
  - System Overview:
    - system_overview/hw_components.md
    - system_overview/sw_components.md
    - system_overview/automation_nodes.md
  - Development:
    - development/dev.md
  - Additional:
    - additional/technical.md
    - additional/compression_rules.md
  - Legal Information:
    - legal.md